# Jekyll configuration for GitHub Pages  
# This file tells GitHub Pages to serve the site directly without Jekyll processing

# Exclude unnecessary files from the published site
exclude:
  - .git
  - .gitignore
  - templates
  - Taskfile.yml
  - package.json
  - package-lock.json
  - node_modules
  - README.md
  - CONTRIBUTING.md
